/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkloadRouteImport } from './routes/workload'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StageGatesRouteImport } from './routes/stage-gates'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as CpaRouteImport } from './routes/cpa'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'

const WorkloadRoute = WorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StageGatesRoute = StageGatesRouteImport.update({
  id: '/stage-gates',
  path: '/stage-gates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaRoute = CpaRouteImport.update({
  id: '/cpa',
  path: '/cpa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/cpa': typeof CpaRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/stage-gates': typeof StageGatesRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRoute
  '/workload': typeof WorkloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/cpa': typeof CpaRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/stage-gates': typeof StageGatesRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRoute
  '/workload': typeof WorkloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/cpa': typeof CpaRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/stage-gates': typeof StageGatesRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRoute
  '/workload': typeof WorkloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/approvals'
    | '/cpa'
    | '/projects'
    | '/reports'
    | '/stage-gates'
    | '/teams'
    | '/templates'
    | '/workload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admin'
    | '/approvals'
    | '/cpa'
    | '/projects'
    | '/reports'
    | '/stage-gates'
    | '/teams'
    | '/templates'
    | '/workload'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/approvals'
    | '/cpa'
    | '/projects'
    | '/reports'
    | '/stage-gates'
    | '/teams'
    | '/templates'
    | '/workload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CpaRoute: typeof CpaRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  StageGatesRoute: typeof StageGatesRoute
  TeamsRoute: typeof TeamsRoute
  TemplatesRoute: typeof TemplatesRoute
  WorkloadRoute: typeof WorkloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workload': {
      id: '/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof WorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-gates': {
      id: '/stage-gates'
      path: '/stage-gates'
      fullPath: '/stage-gates'
      preLoaderRoute: typeof StageGatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa': {
      id: '/cpa'
      path: '/cpa'
      fullPath: '/cpa'
      preLoaderRoute: typeof CpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  ApprovalsRoute: ApprovalsRoute,
  CpaRoute: CpaRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  StageGatesRoute: StageGatesRoute,
  TeamsRoute: TeamsRoute,
  TemplatesRoute: TemplatesRoute,
  WorkloadRoute: WorkloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
