/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StageGatesRouteImport } from './routes/stage-gates'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DspRouteImport } from './routes/dsp'
import { Route as IndexRouteImport } from './routes/index'

const StageGatesRoute = StageGatesRouteImport.update({
  id: '/stage-gates',
  path: '/stage-gates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DspRoute = DspRouteImport.update({
  id: '/dsp',
  path: '/dsp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dsp': typeof DspRoute
  '/projects': typeof ProjectsRoute
  '/stage-gates': typeof StageGatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dsp': typeof DspRoute
  '/projects': typeof ProjectsRoute
  '/stage-gates': typeof StageGatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dsp': typeof DspRoute
  '/projects': typeof ProjectsRoute
  '/stage-gates': typeof StageGatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dsp' | '/projects' | '/stage-gates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dsp' | '/projects' | '/stage-gates'
  id: '__root__' | '/' | '/dsp' | '/projects' | '/stage-gates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DspRoute: typeof DspRoute
  ProjectsRoute: typeof ProjectsRoute
  StageGatesRoute: typeof StageGatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stage-gates': {
      id: '/stage-gates'
      path: '/stage-gates'
      fullPath: '/stage-gates'
      preLoaderRoute: typeof StageGatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsp': {
      id: '/dsp'
      path: '/dsp'
      fullPath: '/dsp'
      preLoaderRoute: typeof DspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DspRoute: DspRoute,
  ProjectsRoute: ProjectsRoute,
  StageGatesRoute: StageGatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
